import { createAppKit } from "@reown/appkit";
import { base, mainnet, polygon } from "@reown/appkit/networks";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import {
  getConnection,
  getChainId,
  watchConnection,
  watchChainId,
} from "@wagmi/core";
import type { Address } from "viem";
import { walletAddress, walletChainId } from "../stores/user";

/**
 * Public Reown/AppKit project id exposed to the client runtime.
 * Required because AppKit runs in browser context.
 */
const projectId = import.meta.env.PUBLIC_REOWN_PROJECT_ID;
if (!projectId) {
  throw new Error("Missing PUBLIC_REOWN_PROJECT_ID environment variable");
}

/**
 * Networks enabled across wallet connect + network switching flows.
 */
const networks: [typeof base, typeof mainnet, typeof polygon] = [
  base,
  mainnet,
  polygon,
];

const wagmiAdapter = new WagmiAdapter({
  projectId,
  networks,
});

const metadata = {
  name: "venturarodriguez.xyz",
  description: "Ventura Rodriguez's personal site",
  url: "https://venturarodriguez.xyz",
  icons: ["https://venturarodriguez.xyz/favicon.ico"],
};

/**
 * Shared AppKit modal singleton for the whole app.
 */
export const appKitModal = createAppKit({
  adapters: [wagmiAdapter],
  networks,
  metadata,
  projectId,
  allowUnsupportedChain: false,
  enableNetworkSwitch: true,
  features: {
    analytics: false,
    swaps: false,
    onramp: false,
  },
  themeMode: "light",
  themeVariables: {
    "--w3m-font-family": "'Lato', sans-serif",
    "--w3m-accent": "var(--color-accent)",
    "--w3m-color-mix-strength": 20,
    "--w3m-color-mix": "var(--color-base-300)",
    "--w3m-border-radius-master": "0px",
  },
});

/**
 * Wagmi config generated by the AppKit wagmi adapter.
 * Use this config for all wagmi core actions/watchers in client code.
 */
export const wagmiConfig = wagmiAdapter.wagmiConfig;

let hasSyncedWalletStores = false;

/**
 * Subscribes once to wallet connection + chain changes and mirrors them to Svelte stores.
 *
 * Idempotent by design: repeated calls are no-ops after the first setup.
 */
export function setupWalletStoreSync(): void {
  if (hasSyncedWalletStores) return;
  hasSyncedWalletStores = true;

  watchConnection(wagmiConfig, {
    onChange() {
      const address = (getConnection(wagmiConfig)?.address ?? undefined) as
        | Address
        | undefined;
      walletAddress.set(address);
      if (!address) {
        walletChainId.set(undefined);
      } else {
        walletChainId.set(getChainId(wagmiConfig));
      }
    },
  });

  watchChainId(wagmiConfig, {
    onChange(chainId) {
      walletChainId.set(chainId);
    },
  });

  const initialConnection = getConnection(wagmiConfig);
  walletAddress.set(initialConnection?.address ?? undefined);
  walletChainId.set(getChainId(wagmiConfig));
}
